export const quizList = [
  {
    id: 1,
    question: "Dois je ralentir maintenant?",
    image: require("../../../assets/Quiz/image1.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["oui"],
  },
  {
    id: 2,
    question: " j'entre dans la zone d'incertitude ",
    image: require("../../../assets/Quiz/image2.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["oui"],
  },
  {
    id: 3,
    question: "Plus je roule vite, plus mon champ visuel se reduit",
    image: require("../../../assets/Quiz/image3.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["oui"],
  },
  {
    id: 4,
    question: "Conduire avec un champ visuel de moins de 120 degres est",
    image: require("../../../assets/Quiz/image4.jpeg"),
    possibilites: ["conseille", "Tolere", "Interdit"],
    reponses: ["Interdit"],
  },
  {
    id: 5,
    question: "ce panneau annonce un virage a droite:",
    image: require("../../../assets/Quiz/image5.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
  {
    id: 6,
    question: "je dois tourner a gauche",
    image: require("../../../assets/Quiz/image6.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["oui"],
  },
  {
    id: 7,
    question:
      "l'acces a cette route est interdite aux vehicules de plus de 3 metres de hauteur",
    image: require("../../../assets/Quiz/image7.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
  {
    id: 8,
    question: "Ce signal indique",
    image: require("../../../assets/Quiz/image8.jpeg"),
    possibilites: [
      "Un hotel",
      "Un etablissement hospitalier",
      "Une piste pour helicoptere",
    ],
    reponses: ["Un etablissement hospitalier"],
  },
  {
    id: 9,
    question: "Dois je ralentir a 50 metres seulement?",
    image: require("../../../assets/Quiz/image1.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
  {
    id: 10,
    question: "Plus je roule vite, plus mon angle de vision augmente",
    image: require("../../../assets/Quiz/image3.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
  {
    id: 11,
    question: "ce panneau annonce un virage a gauche",
    image: require("../../../assets/Quiz/image5.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
  {
    id: 12,
    question: "je dois me placer sur la voie a gauche",
    image: require("../../../assets/Quiz/image6.jpeg"),
    possibilites: ["oui", "non"],
    reponses: ["non"],
  },
];
